{{- if .Values.ragWorker.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rag-worker
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ragWorker.irsaRoleArn | quote }}
  labels:
    app: rag-worker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: medilink-hub
{{- end }}
