{{- $svc := index .Values.services "user-service" }}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-service
    app.kubernetes.io/part-of: medilink-hub
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: sa-user-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: user-service
        image: {{ .Values.global.imageRegistry }}/medilink/user-service:{{ .Values.global.imageTag }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8001
        env:
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.global.awsRegion | quote }}
        - name: JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: medilink-jwt-keys
              key: private.pem
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: medilink-jwt-keys
              key: public.pem
        livenessProbe:
          httpGet: { path: /health, port: http }
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet: { path: /health, port: http }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: {{ $svc.resources.requests.cpu | quote }}
            memory: {{ $svc.resources.requests.memory | quote }}
          limits:
            cpu: {{ $svc.resources.limits.cpu | quote }}
            memory: {{ $svc.resources.limits.memory | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: user-service
{{- end }}
